services:
  app:
    build:
      dockerfile: Dockerfile-spring
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    container_name: postgres
    build:
      dockerfile: Dockerfile-psql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: {}